import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";
import toast, { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Onboarding - FlexLogic",
  description: "Generated by create next app",
};

const inter = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster
            position="bottom-right"
            reverseOrder={false}
            toastOptions={{
              style: {
                padding: "16px",
              },
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
